Repository ucsb-cs156-m23/proj-gauchoride-m23-9am-1, pull requests merged in 2023-08, with the labels that each got.

#15 added cellPhone entity
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
Labels: FIXME-see CR

#16 added PUT request and route /api/userprofile
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
Labels: FIXME-needs team CR

#19 adjusted backend and backend testing
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Ride.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RideControllerTests.java
Labels: FIXME-see CR

#47 added ROLE_RIDER to RoleInterceptor and tests
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptorTests.java
Labels: FIXME-description

#28 Made frontend changes to Ride Requests page in order to include the new pickup room and notes fields
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/main/pages/Ride/RideRequestCreatePage.js
  frontend/src/main/pages/Ride/RideRequestEditPage.js
  frontend/src/tests/components/Ride/RideForm.test.js
  frontend/src/tests/components/Ride/RideTable.test.js
  frontend/src/tests/pages/Ride/RideRequestCreatePage.test.js
  frontend/src/tests/pages/Ride/RideRequestEditPage.test.js
Labels: FIXME-see CR, FIXME-title

#39 Add Get all driver shifts method in Shift controller
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/ShiftRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/ShiftControllerTests.java
Labels: 10, MergeCandidate-CI

#54 Added 'ROLE_RIDER' to shift controller and tests and Removed DRIVER permission for create/edit/delete
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/ShiftControllerTests.java
Labels: 10

#61 Added GET /api/drivers/all and DriverController + Tests
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriversControllerTests.java
Labels: FIXME-see CR

#65 Implemented driver dashboard page and dashboard page tests
  frontend/src/main/pages/Drivers/driverDashboardPage.js
  frontend/src/tests/pages/Drivers/driverDashboardPage.test.js
Labels: 10, MergeCandidate-CI

#63 Created DriverTable component and storybook entry
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Drivers/DriverTable.js
  frontend/src/stories/components/Drivers/DriverTable.stories.js
  frontend/src/tests/components/Drivers/DriverTable.test.js
Labels: 10, MergeCandidate-CI

#67 Added RiderApplication Form, Stories, and Tests
  frontend/src/fixtures/riderApplicationFixtures.js
  frontend/src/main/components/RiderApplication/RiderApplicationForm.js
  frontend/src/stories/components/RiderApplication/RiderApplicationForm.stories.js
  frontend/src/tests/components/RiderApplication/RiderApplicationForm.test.js
Labels: 10, MergeCandidate-CI

#69 Added Shift Form, Tables, Stories, and Tests
  frontend/src/App.js
  frontend/src/fixtures/shiftFixtures.js
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/main/components/Shift/ShiftTable.js
  frontend/src/main/pages/Shift/ShiftPage.js
  frontend/src/main/utils/ShiftUtils.js
  frontend/src/stories/components/Shift/ShiftForm.stories.js
  frontend/src/stories/components/Shift/ShiftTable.stories.js
  frontend/src/stories/pages/Shift/Shift.stories.js
  frontend/src/tests/components/Shift/ShiftForm.test.js
  frontend/src/tests/components/Shift/ShiftTable.test.js
  frontend/src/tests/pages/ShiftPage.test.js
  frontend/src/tests/utils/ShiftUtils.test.js
Labels: 10, MergeCandidate-CI

#71 Added Driver Edit and Create Page + Tests
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Shift/ShiftForm.js
  frontend/src/main/pages/Shift/ShiftCreatePage.js
  frontend/src/main/pages/Shift/ShiftEditPage.js
  frontend/src/tests/pages/Drivers/driverDashboardPage.test.js
  frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
  frontend/src/tests/pages/Shift/ShiftEditPage.test.js
  frontend/src/tests/pages/Shift/ShiftPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
Labels: FIXME-see CR
